name: Python Pull Request WorkFlow
on:
  pull_request:
    branches:
      [main]
  

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@latest
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
